import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'AI Image Detector - Professional Image Authenticity Analysis',
  description: 'Upload any image and our advanced AI models will analyze whether it was generated by AI or captured by a real camera. Powered by ResNet-50 and Vision Transformer.',
  keywords: 'AI image detection, deepfake detection, synthetic image analysis, computer vision',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  )
}
