'use client'

import { useState } from 'react'
import ImageUploader from '@/components/ImageUploader'
import ResultsDisplay from '@/components/ResultsDisplay'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

export default function Home() {
  const [result, setResult] = useState(null)
  const [isLoading, setIsLoading] = useState(false)

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
      <Header />
      
      <main className="container mx-auto px-4 py-8">
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-gray-800 mb-4">
            AI Image Detection System
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Upload any image and our advanced AI models will analyze whether 
            it was generated by AI or captured by a real camera.
          </p>
          
          {/* Model Info Cards */}
          <div className="grid md:grid-cols-2 gap-6 mt-8 max-w-4xl mx-auto">
            <div className="bg-white rounded-lg shadow-md p-6">
              <div className="text-blue-600 font-semibold text-lg">ResNet-50</div>
              <div className="text-gray-600 text-sm">Convolutional Neural Network</div>
              <div className="text-2xl font-bold text-green-600 mt-2">93.5% Accuracy</div>
            </div>
            
            <div className="bg-white rounded-lg shadow-md p-6">
              <div className="text-purple-600 font-semibold text-lg">Vision Transformer</div>
              <div className="text-gray-600 text-sm">Attention-based Architecture</div>
              <div className="text-2xl font-bold text-green-600 mt-2">98.9% Accuracy</div>
            </div>
          </div>
        </div>

        <div className="grid lg:grid-cols-2 gap-8 max-w-6xl mx-auto">
          {/* Upload Section */}
          <div className="bg-white rounded-xl shadow-lg p-6">
            <h2 className="text-2xl font-semibold text-gray-800 mb-6">
              Upload Image for Analysis
            </h2>
            <ImageUploader 
              onResult={setResult} 
              onLoading={setIsLoading}
            />
          </div>

          {/* Results Section */}
          <div className="bg-white rounded-xl shadow-lg p-6">
            <h2 className="text-2xl font-semibold text-gray-800 mb-6">
              Analysis Results
            </h2>
            <ResultsDisplay 
              result={result} 
              isLoading={isLoading}
            />
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
